use AFCARS

set nocount on

select FY, STATE, FIPSCODE, SEX, HISORGIN, 
TotalRem, PHYABUSE, SEXABUSE, NEGLECT, AAPARENT, DAPARENT, AACHILD, 
DACHILD, CHILDIS, CHBEHPRB, PRTSDIED, PRTSJAIL, NOCOPE, ABANDMNT, RELINQSH, HOUSING, 
AgeAtEnd, Entered, Exited, DISREASN
from dbo.FosterCare
where FY>=2000